#!/bin/bash

#only for linux check
#OS="`uname`"
#$OS_req='Linux'
#if [$OS -eq $OS_req  ]
#then
set -e #to detect error
wget https://github.com/Bashmug/mew/archive/test-1.zip #downloading sources
#zip
unzip test-2.zip #extract Downloaded Zip
#to install mew
./mew
