#!/bin/bash
# Why Mew in as a translator
# short name
#its a pokemon
# it can talk to every pokemon
# its cute
# its legendary
# its cute
echo "Mew - μ"

case "$OSTYPE" in
  solaris*) echo "SOLARIS" ;;
  darwin*)  echo "OSX" ;;
  linux*)   echo "LINUX" ;;
  bsd*)     echo "BSD" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac
