#!/usr/bin/env python

import sys
from MEW import MEW

packageManager = sys.argv[1]
commands = []
arguments = []

for item in sys.argv[2:]:
	if item.startswith("@"):
		arguments.append(item)
	else:
		commands.append(item)

commands = ' '.join(commands)


mew = MEW(packageManager, commands, arguments)
print mew.package_manager
print mew.translated