#!/bin/bash
n=0
for i
do
  echo $i
  array[$n]=$i
  ((++n))
done
case "${array[0]}" in
  "-S") apt install ${array[1]}
  ;;
  "-R") apt remove ${array[1]}
  ;;
  "-Syy") apt update
  ;;
  "-Qu") apt list --upgradable
  ;;
  "-Syu") apt upgrade
  ;;
  *) echo "send a pull request to https://github.com/Bashmug/mew or make it an issue if its not working"
esac
