#!/bin/bash
n=0
for i
do
  echo $i
  array[$n]=$i
  ((++n))
done

echo array testing first two elements
echo ${array[0]}
echo ${array[1]}

case "${array[0]}" in
  "-U") apt update ${array[1]}
  ;;
  "-S") apt install ${array[1]}
  ;;
esac
