#!/bin/bash
n=0
for i
do
  array[$n]=$i
  ((++n))
done
case "${array[0]}" in
  "install") echo command translated to --> apt install ${array[1]}
  apt install ${array[1]}
  ;;
  "--nodeps")
          case "${array[1]}" in
          "remove") echo command translated to --> apt remove ${array[2]}
          apt remove ${array[2]}
          ;;
          *)echo "send a pull request to https://github.com/Bashmug/mew or make it an issue if its not working"
          ;;
          esac
  ;;
  "remove") echo command translated to --> apt autoremove ${array[1]}
  apt autoremove ${array[1]}
  ;;
  *) echo "send a pull request to https://github.com/Bashmug/mew or make it an issue if its not working"
  ;;
esac
