#!/bin/bash
n=0
for i
do
  echo $i
  array[$n]=$i
  ((++n))
done

echo array testing first two elements
echo ${array[0]}
echo ${array[1]}

case "${array[0]}" in
  "update") echo update check
  ;;
  "install") pacman -S ${array[1]}
  ;;
esac
